@InventoryApi = http://localhost:5018
@ProductId = 22222222-2222-2222-2222-222222222222

PUT {{InventoryApi}}/stock/{{ProductId}}
Content-Type: application/json

{
  "availableQuantity": 10
}

###

GET {{InventoryApi}}/stock/{{ProductId}}
Accept: application/json
